[program:octane]
priority=5
autostart=true
autorestart=true
user=www-data
command=php /var/www/html/artisan octane:start --server=roadrunner --host=127.0.0.1 --port=8000 --workers=%(ENV_OCTANE_WORKERS)s --max-requests=500 --rr-config=/var/www/html/.fly/rr.yaml
stopwaitsecs=65
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
