<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\Callout;
use App\Services\CalloutService;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class CalloutController extends Controller
{
    protected CalloutService $calloutService;

    public function __construct(CalloutService $calloutService)
    {
        $this->calloutService = $calloutService;
    }

    /**
     * The numbers callout alerts are sent from, so people can save them as contacts.
     * The primary (Twilio) number is returned to everyone; the backup (TextMagic)
     * number is only returned to duty officers and platform admins.
     */
    public function contactNumbers(Request $request)
    {
        $user = $request->user();
        $canSeeBackup = $user && $user->hasRole(['platform_admin', 'duty_officer']);

        return response()->json([
            'primary_sms_number' => config('callouts.numbers.primary_sms'),
            'backup_sms_number' => $canSeeBackup ? config('callouts.numbers.backup_sms') : null,
        ]);
    }

    /**
     * Create a new callout.
     */
    public function store(Request $request)
    {
        if (!$request->user()->hasApprovedClub()) {
            abort(403, 'You must be an approved club member to open callouts.');
        }

        // A callout relies on us being able to reach the caver, so their own number must be
        // verified first. The frontend prompts for this; this is the server-side guard.
        if (!$request->user()->phoneVerified()) {
            return response()->json([
                'message' => 'Please verify your phone number before creating a callout.',
                'code' => 'phone_unverified',
            ], 422);
        }

        $data = $request->validate([
            'cave_id' => 'nullable|exists:caves,id',
            'exit_cave_id' => 'nullable|exists:caves,id',
            'callout_time' => 'required|date|after:now',
            'description' => 'nullable|string',
            'trip_plan' => 'required|string',
            'car_details' => 'nullable|string', // kept for backward compatibility
            'car_registration' => 'required|string',
            'car_parking' => 'required|string',
            'location_data' => 'nullable|array',
            'team_details' => 'nullable|string',
            'trip_id' => 'nullable|exists:trips,id',
            'participants' => 'required|array|min:1',
            'participants.*.user_id' => 'nullable|exists:users,id',
            'participants.*.name' => 'required|string',
            'participants.*.phone' => 'nullable|string',
            'participants.*.email' => 'nullable|email',
        ]);

        $data['request_data'] = [
            'ip' => $request->ip(),
            'user_agent' => $request->userAgent(),
        ];

        try {
            $callout = $this->calloutService->create($request->user(), $data);

            return response()->json([
                'message' => 'Callout activated successfully.',
                'callout' => $callout,
            ], 201);
        } catch (Exception $e) {
            Log::error('Callout creation failed', ['error' => $e->getMessage(), 'user' => $request->user()->id]);

            return response()->json(['message' => $e->getMessage()], 422);
        }
    }

    /**
     * Cancel a callout.
     *
     * This route is intentionally guest-accessible so that cave parties can cancel
     * their own callout from any device without needing to be logged in.
     *
     * Callout IDs are 16-character cryptographically random strings (generated by
     * Illuminate\Support\Str::random(16)), making brute-force enumeration
     * computationally infeasible. The ID is shared only with the party who created
     * the callout and is treated as a capability token — possession of the ID
     * is sufficient proof of authorisation to cancel.
     */
    public function cancel(Request $request, $id)
    {
        $callout = Callout::with('participants')->findOrFail($id);

        // If logged in, ensure user is either the creator OR a participant (or admin)
        if (Auth::check()) {
            $isCreator = Auth::user()->id === $callout->user_id;
            $isParticipant = $callout->participants->contains('user_id', Auth::user()->id);
            $isAdmin = Auth::user()->is_admin;

            if (!$isCreator && !$isParticipant && !$isAdmin) {
                abort(403, 'Unauthorized. You must be a participant in this callout to cancel it.');
            }
        }

        // Record cancellation metadata snapshot
        $callout->update([
            'cancelled_ip' => $request->ip(),
            'cancelled_user_agent' => $request->userAgent(),
            'cancelled_location' => $request->input('location'), // Optional location from frontend
        ]);

        $trip = $this->calloutService->cancel($callout);

        return response()->json([
            'message' => 'Callout cancelled successfully.',
            'trip_id' => $trip ? $trip->short_id : null,
        ]);
    }

    public function show($id)
    {
        $callout = Callout::with(['participants', 'cave', 'exitCave'])->findOrFail($id);

        // Limit sensitive fields for unauthenticated users
        if (!auth()->check()) {
            return response()->json(['data' => [
                'id' => $callout->id,
                'status' => $callout->status,
                'callout_time' => $callout->callout_time,
                'cave' => $callout->cave ? ['id' => $callout->cave->id, 'name' => $callout->cave->name] : null,
                'exit_cave' => $callout->exitCave ? ['id' => $callout->exitCave->id, 'name' => $callout->exitCave->name] : null,
                'participant_count' => $callout->participants->count(),
            ]]);
        }

        return response()->json(['data' => $callout]);
    }

    /**
     * Get Open callouts for the public map.
     */
    public function active()
    {
        $callouts = Callout::query()
            ->whereIn('status', ['active', 'triggered'])
            ->with(['cave:id,name,location_lat,location_lng,location_name', 'participants'])
            ->get()
            ->map(function ($callout) {
                // Resolve location: Cave takes precedence, then manual location data
                $lat = null;
                $lng = null;
                $caveName = 'Unknown Location';

                if ($callout->cave) {
                    $lat = $callout->cave->location_lat;
                    $lng = $callout->cave->location_lng;
                    $caveName = $callout->cave->name;
                } elseif (!empty($callout->location_data) && isset($callout->location_data['latitude'], $callout->location_data['longitude'])) {
                    $lat = $callout->location_data['latitude'];
                    $lng = $callout->location_data['longitude'];
                }

                return [
                    'id' => $callout->id,
                    'cave_name' => $caveName,
                    'lat' => $lat,
                    'lng' => $lng,
                ];
            });

        return response()->json(['data' => $callouts]);
    }
}
