name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, sqlite3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Install frontend dependencies
        run: cd frontend && yarn install --frozen-lockfile
      - name: Build frontend
        run: cd frontend && yarn run build
      - name: Copy .env if needed
        run: |
          if [ ! -f .env ]; then cp .env.example .env; fi
      - name: Generate app key
        run: php artisan key:generate
      - name: Set up SQLite database
        run: |
          touch database.sqlite
      - name: Run migrations
        run: php artisan migrate --force
      - name: Run tests
        run: vendor/bin/phpunit
      - name: Make HTTP request # Ensure the api is up. Helps with postgres going to sleep
        run: |
          curl -s https://subterra.world/api/livez > /dev/null; sleep 15
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}