name: Test
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, sqlite3
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Copy .env if needed
        run: |
          if [ ! -f .env ]; then cp .env.example .env; fi
      - name: Generate app key
        run: php artisan key:generate
      - name: Set up SQLite database
        run: |
          touch database/database.sqlite
      - name: Run migrations
        run: php artisan migrate --force
      - name: Run tests
        run: vendor/bin/phpunit